http:
  ip: 127.0.0.1
  port: 8081
  env: prd
asset:
  page:
    path: web
i18n:
  path: conf/i18n
job:
  # xxl服务端地址
  server-url: http://10.10.10.223:5678/xxl-job-admin
  # 任务执行 token, 必须与服务端配置一致
  token: pet-api-qaz
  # 执行器名称，服务端添加执行器时使用该名称
  executor-name: woof-job-exec

db:
  # write/read db
  - name: wdb
    host: database-prd.cluster-cp2owmca8n8a.ap-southeast-1.rds.amazonaws.com
    port: 3306
    database: woof
    username: admin
    password: Qq321654987!#%
    show-sql: true
    params: charset=utf8mb4&parseTime=True&loc=UTC
  # read-only db
  - name: rdb
    host: database-prd.cluster-ro-cp2owmca8n8a.ap-southeast-1.rds.amazonaws.com
    port: 3306
    database: woof
    username: admin
    password: Qq321654987!#%
    show-sql: true
    params: charset=utf8mb4&parseTime=True&loc=UTC
# redis configuration
redis:
  db: 2
  addr: 172.31.25.206:7000,172.31.25.206:7001,172.31.25.206:7002,172.31.25.206:7003,172.31.25.206:7004,172.31.25.206:7005
  password:
  tls: false
  cluster: true
# mogodb
mongo:
  host: 172.31.25.206
  port: 27017
  auth-source: admin
  username: root
  password: Pet654#$
  database: woof
zap:
  level: debug
  prefix: ''
  format: text
  director: logs
  encode-level: cap
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true
auth:
  skip-url: /favicon.ico,/job/**,/run,/kill,/log,/beat,/idleBeat,/sys/**,/demo/**
  fixed-token-url: /login/**,/portal/login/**,/system/setting,/system/setting/**,/portal/system/setting,/portal/system/setting/**,/twitter/**,/portal/twitter/**
  fix-token:
  captcha-key:
portal:
  url:
#aws-s3 config
aws-s3:
  region:
  access-key-id:
  access-key-secret:
  bucket:
  preview-url:

#mail config
mail:
  server:
  supportDomain:

twitter:
  clientId:
  clientSecret:
  redirectUrl:

google:
  captcha-key: