// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"goboot/cmd/portal/conf"
	"goboot/cmd/portal/server"
	"goboot/internal/config"
	"goboot/internal/handler"
	"goboot/internal/repository"
	"goboot/internal/repository/repo"
	"goboot/internal/service"
	"goboot/pkg/aws/s3"
	"goboot/pkg/helper/sid"
	"goboot/pkg/mail"
)

// Injectors from wire.go:

func newApp() (*server.App, func(), error) {
	portalConf := ConfProvider()
	logger := LoggerProvider(portalConf)
	client := repo.NewRedis(portalConf)
	app := server.NewServerHTTP(logger, portalConf, client)
	return app, func() {
	}, nil
}

// wire.go:

// 全局唯一id
var sidSet = wire.NewSet(sid.NewSid)

var confSet = wire.NewSet(ConfProvider, LoggerProvider, wire.Bind(new(config.Conf), new(*conf.PortalConf)))

// http服务
var serverSet = wire.NewSet(server.NewServerHTTP)

// sys相关集合
var sysSrvSet = wire.NewSet(service.NewAppVersionService, service.NewSysSettingService)

var sysRepoSet = wire.NewSet(repository.NewSysSettingRepository, repository.NewSysVersionRepository)

// user相关集合
var userSrvSet = wire.NewSet(service.NewSysDeviceService, service.NewUserService)

var userRepoSet = wire.NewSet(repository.NewSysDeviceRepository, repository.NewUserRepository)

// 集合组
var handlerGroup = wire.NewSet(handler.NewHandler)

var srvGroup = wire.NewSet(conf.NewS3Conf, s3.NewS3, mail.NewSender, service.NewService, service.NewImageService, sysSrvSet,
	userSrvSet,
)

var repoGroup = wire.NewSet(repo.NewWDB, repo.NewRDB, repo.NewRedis, repo.NewMongoDB, repo.NewRepository, sysRepoSet,
	userRepoSet,
)
